var game = new Phaser.Game(1500,1000, Phaser.AUTO);
game.state.add('levelone', test.levelone);
game.state.add('leveltwo', test.leveltwo);
game.state.add('levelthree', test.levelthree);
game.state.add('startpage', test.startpage);
game.state.add('completionpage', test.completionpage);
game.state.add('completionpage1', test.completionpage1);
game.state.add('completionpage2', test.completionpage2);
game.state.add('completionpage3', test.completionpage3);
game.state.add('storypage', test.storypage);
game.state.add('gameover', test.gameover);
game.state.add('youwin', test.youwin);
game.state.add('finalboss', test.finalboss);
game.state.add('storypage2', test.storypage2);
game.state.add('storypage3', test.storypage3);
game.state.add('storypage4', test.storypage4);
game.state.add('storypage5', test.storypage5);
game.state.start('startpage');